// bookstore/src/app/components/book-list/book-list.component.ts
import { Component, OnInit  } from '@angular/core';
import { BookService } from '../../services/book.service';
import { Book } from '../../models/book.model';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';

@Component({
  selector: 'app-book-list',
  templateUrl: './book-list.component.html',
  imports: [CommonModule, RouterModule],
})
export class BookListComponent implements OnInit {
  constructor(private bookService: BookService, private router: Router) {}

  deleteBook(bookId: number) {
    this.bookService.deleteBook(bookId).subscribe(() => {
      this.books = this.books.filter((book) => book.id !== bookId);
    });
  }
  books: Book[] = [];


  ngOnInit(): void {
    this.bookService.getBooks().subscribe((data) => {
      this.books = data;
    });
  }
}

<h2 class="mb-4">All Books</h2>

<div class="container">
  <div class="card mb-4" *ngFor="let book of books">
    <div class="row g-0 align-items-center">
      <div class="col-md-3 d-flex justify-content-center p-3">
        <img [src]="book.imageUrl" class="img-fluid rounded" [alt]="book.title"
          style="max-width: 150px; object-fit: contain;" />
      </div>
      <div class="col-md-9">
        <div class="card-body d-flex flex-column justify-content-between h-100">
          <div>
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text mb-1"><strong>Author:</strong> {{ book.author }}</p>
            <p class="card-text mb-1"><strong>Rating:</strong> {{ book.rating }}</p>
            <p class="card-text mb-1"><strong>Price:</strong> ${{ book.price }}</p>
            <p class="card-text"><small class="text-muted">Published on {{ book.publishDate }}</small></p>
          </div>
          <div class="mt-3 d-flex justify-content-end gap-2">
            <a class="btn btn-primary btn-sm" [routerLink]="['/edit', book.id]">Edit</a>
            <button class="btn btn-danger btn-sm" (click)="deleteBook(book.id)">Delete</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// bookstore-react/src/components/BookList.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { API_BASE_URL } from '../CONSTANTS';

const BookList = () => {
  const [books, setBooks] = useState([]);

  const loadBooks = async () => {
    try {
      const response = await axios.get(`${API_BASE_URL}/books`);
      setBooks(response.data);
    } catch (error) {
      console.error('Error loading books:', error);
    }
  };

  useEffect(() => {
    loadBooks();
  }, []);

  const deleteBook = async (id) => {
    try {
      await axios.delete(`${API_BASE_URL}/books/${id}`);
      loadBooks();
    } catch (error) {
      console.error('Error deleting book:', error);
    }
  };

  return (
    <div>
      <h2>All Books</h2>
      {books.map((book) => (
        <div className="card mb-3" key={book.id}>
          <div className="row g-0">
            <div className="col-md-3">
              <img
                src={book.imageUrl}
                alt={book.title}
                className="img-fluid rounded-start"
                style={{ objectFit: 'cover', height: '100%' }}
              />
            </div>
            <div className="col-md-9">
              <div className="card-body">
                <h5 className="card-title">{book.title}</h5>
                <p className="card-text"><strong>Author:</strong> {book.author}</p>
                <p className="card-text"><strong>Price:</strong> ${book.price.toFixed(2)}</p>
                <p className="card-text"><strong>Rating:</strong> {book.rating}</p>
                <p className="card-text"><strong>Published:</strong> {new Date(book.publishDate).toLocaleDateString()}</p>

                <div className="mt-3 d-flex gap-2">
                  <Link to={`/edit/${book.id}`} className="btn btn-primary">Edit</Link>
                  <button className="btn btn-danger" onClick={() => deleteBook(book.id)}>Delete</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default BookList;
