// bookstore-react/src/components/CreateBook.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { API_BASE_URL } from '../CONSTANTS';

const CreateBook = () => {
  const [book, setBook] = useState({
    title: '',
    author: '',
    price: '',
    publishDate: '',
    imageUrl: '',
    rating: '',
  });

  const navigate = useNavigate();

  const handleChange = (e) => {
    setBook({ ...book, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post(`${API_BASE_URL}/books`, book);
      navigate('/');
    } catch (error) {
      console.error('Error creating book:', error);
    }
  };

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h2>Create New Book</h2>
        <button className="btn btn-secondary" onClick={() => navigate('/')}>
          Back
        </button>
      </div>

      <form onSubmit={handleSubmit}>
        <div className="mb-3">
          <label htmlFor="title" className="form-label">Title</label>
          <input
            type="text"
            id="title"
            name="title"
            className="form-control"
            value={book.title}
            onChange={handleChange}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="author" className="form-label">Author</label>
          <input
            type="text"
            id="author"
            name="author"
            className="form-control"
            value={book.author}
            onChange={handleChange}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="price" className="form-label">Price ($)</label>
          <input
            type="number"
            step="0.01"
            min="0"
            id="price"
            name="price"
            className="form-control"
            value={book.price}
            onChange={handleChange}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="publishDate" className="form-label">Publish Date</label>
          <input
            type="date"
            id="publishDate"
            name="publishDate"
            className="form-control"
            value={book.publishDate}
            onChange={handleChange}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="imageUrl" className="form-label">Image URL</label>
          <input
            type="text"
            id="imageUrl"
            name="imageUrl"
            className="form-control"
            value={book.imageUrl}
            onChange={handleChange}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="rating" className="form-label">Rating</label>
          <input
            type="number"
            step="0.1"
            min="0"
            max="5"
            id="rating"
            name="rating"
            className="form-control"
            value={book.rating}
            onChange={handleChange}
            required
          />
        </div>

        <button type="submit" className="btn btn-success">Create Book</button>
      </form>
    </div>
  );
};

export default CreateBook;

// bookstore/src/app/components/create-book/create-book.component.ts
import { Component } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { BookService } from '../../services/book.service';
import { Book } from '../../models/book.model';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-create-book',
  templateUrl: './create-book.component.html',
  imports: [FormsModule, RouterModule],
})
export class CreateBookComponent {
  book: Partial<Book> = {};

  constructor(private bookService: BookService, private router: Router) {}

  onSubmit() {
    // match MySQL DATETIME format
    const adjustedBook = {
      ...this.book,
      publishDate: this.book.publishDate + ' 00:00:00'
    };

    this.bookService.createBook(adjustedBook).subscribe({
      next: () => this.router.navigate(['/']),
      error: err => console.error('Error creating book', err),
    });
  }
}

<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Create New Book</h2>
    <a routerLink="/" class="btn btn-outline-secondary">Back</a>
  </div>

  <form (ngSubmit)="onSubmit()" #bookForm="ngForm">
    <div class="mb-3">
      <label for="title" class="form-label">Title</label>
      <input type="text" id="title" class="form-control" required [(ngModel)]="book.title" name="title">
    </div>

    <div class="mb-3">
      <label for="author" class="form-label">Author</label>
      <input type="text" id="author" class="form-control" required [(ngModel)]="book.author" name="author">
    </div>

    <div class="mb-3">
      <label for="price" class="form-label">Price ($)</label>
      <input type="number" step="0.01" min="0" id="price" class="form-control" required [(ngModel)]="book.price"
        name="price">
    </div>

    <div class="mb-3">
      <label for="publishDate" class="form-label">Publish Date</label>
      <input type="date" id="publishDate" class="form-control" required [(ngModel)]="book.publishDate"
        name="publishDate">
    </div>

    <div class="mb-3">
      <label for="imageUrl" class="form-label">Image URL</label>
      <input type="text" id="imageUrl" class="form-control" required [(ngModel)]="book.imageUrl" name="imageUrl">
    </div>

    <div class="mb-3">
      <label for="rating" class="form-label">Rating</label>
      <input type="number" step="0.1" min="0" max="5" id="rating" class="form-control" required
        [(ngModel)]="book.rating" name="rating">
    </div>

    <button type="submit" class="btn btn-success">Create Book</button>
  </form>
</div>
